# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ShahRukh's Blog
email: sathar@cs.stonybrook.edu
description: > # this means to ignore newlines until "baseurl:"
  I dabble in Computer Vision and Machine Learning
baseurl: "/about" # the subpath of your site, e.g. /blog
url: "https://shahrukhathar.github.io" # the base hostname & protocol for your site
twitter_username: shahrukh_athar
github_username:  srxdev0619

#Authors
shahrukh_athar:
    name: ShahRukh Athar
    web: http://shahrukhathar.github.io/
victor_lempitsky:
    name: Victor Lempitsky
    web: http://sites.skoltech.ru/compvision/members/vilem/
evgeny_burnaev:
    name: Evgeny Burnaev
    web: https://faculty.skoltech.ru/people/evgenyburnaev

# Build settings
markdown: kramdown
future: true

theme: jekyll-theme-midnight